name: 'FSJ_DATA_FOUNDATION'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  FSJ_DATA_FOUNDATION:
    # etl-fornecedores:
    #   +materialized: incremental
    # etl-vendas:
    #   +materialized: incremental
    # etl-vendas-pagamentos:
    #   +materialized: incremental
    # etl-devolucoes:
    #   +materialized: incremental
    # comprasdemandaconfig:
    #   +materialized: table
    # etl-produtos:
    #   +materialized: incremental
    # silver:
    #   +materialized: table
    #   +schema: silver
    # gold:
    #   +materialized: view
    #   +schema: gold
    etl-produtos:
       +materialized: incremental

vars:
  'dbt_date:time_zone': 'America/São Paulo'